local ArenaService = require(script.ArenaService)
local ClassService = require(script.ClassService)
local WeaponService = require(script.WeaponService)
local MatchModeService = require(script.MatchModeService)
local RoundService = require(script.RoundService)
local PlayerDataService = require(script.PlayerDataService)
local CosmeticsService = require(script.CosmeticsService)
local ClanService = require(script.ClanService)
local MonetizationService = require(script.MonetizationService)
local CombatService = require(script.CombatService)
local LeaderboardService = require(script.LeaderboardService)
local DummyService = require(script.DummyService)
local BossService = require(script.BossService)
local BotService = require(script.BotService)
local DynamicEventService = require(script.DynamicEventService)
local CoinPickupService = require(script.CoinPickupService)

ArenaService.Init()
ClassService.Init()
WeaponService.Init()
MatchModeService.Init()
RoundService.Init()
PlayerDataService.Init()
CosmeticsService.Init()
ClanService.Init()
MonetizationService.Init()
CombatService.Init()
LeaderboardService.Init()
DummyService.Init()
BossService.Init()
BotService.Init()
DynamicEventService.Init()
CoinPickupService.Init()
