local Localization = require(script.Localization)
local MenuUI = require(script.MenuUI)
local LanguageUI = require(script.LanguageUI)
local RoundUI = require(script.RoundUI)
local ClassSelectUI = require(script.ClassSelectUI)
local WeaponSelectUI = require(script.WeaponSelectUI)
local WeaponSkinsUI = require(script.WeaponSkinsUI)
local GameModeUI = require(script.GameModeUI)
local MatchModeUI = require(script.MatchModeUI)
local ArenaUI = require(script.ArenaUI)
local BotUI = require(script.BotUI)
local CosmeticsUI = require(script.CosmeticsUI)
local ClanUI = require(script.ClanUI)
local SquadUI = require(script.SquadUI)
local LeaderboardUI = require(script.LeaderboardUI)
local BottomHUD = require(script.BottomHUD)
local NotificationUI = require(script.NotificationUI)
local CombatController = require(script.CombatController)
local CombatVFX = require(script.CombatVFX)

Localization.Init()
MenuUI.Init()
LanguageUI.Init()
RoundUI.Init()
MatchModeUI.Init()
GameModeUI.Init()
ArenaUI.Init()
BotUI.Init()
ClassSelectUI.Init()
WeaponSelectUI.Init()
WeaponSkinsUI.Init()
CosmeticsUI.Init()
ClanUI.Init()
SquadUI.Init()
LeaderboardUI.Init()
BottomHUD.Init()
NotificationUI.Init()
CombatController.Init()
CombatVFX.Init()
