local MenuUI = require(script.MenuUI)
local RoundUI = require(script.RoundUI)
local ClassSelectUI = require(script.ClassSelectUI)
local GameModeUI = require(script.GameModeUI)
local MatchModeUI = require(script.MatchModeUI)
local ArenaUI = require(script.ArenaUI)
local BotUI = require(script.BotUI)
local CosmeticsUI = require(script.CosmeticsUI)
local ClanUI = require(script.ClanUI)
local LeaderboardUI = require(script.LeaderboardUI)
local BottomHUD = require(script.BottomHUD)
local NotificationUI = require(script.NotificationUI)
local CombatController = require(script.CombatController)
local CombatVFX = require(script.CombatVFX)

MenuUI.Init()
RoundUI.Init()
ClassSelectUI.Init()
GameModeUI.Init()
MatchModeUI.Init()
ArenaUI.Init()
BotUI.Init()
CosmeticsUI.Init()
ClanUI.Init()
LeaderboardUI.Init()
BottomHUD.Init()
NotificationUI.Init()
CombatController.Init()
CombatVFX.Init()
